### ISSUE TITLE
(log) Debug log for analytics returned should simply print the length of the slice.

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-pump#159] opened 2019-10-17 16:03 UTC
When printing `redis.Values`, which is `[]interface{}`

Output looks like this:

https://github.com/TykTechnologies/tyk-pump/blob/master/storage/redis.go#L245-L247

```
Analytics returned: [[[222 0 27 166 77 101 116 104 111 100 164 80 79 83 84 164 72 111 115 116 191 101 115 98 73 110 116 101 114 110 97 108 76 66 46 112 111 115 116 115 118 99 115 46 99 111 109 58 57 48 57 48 164 80 97 116 104 183 47 109 97 47 83 105 110 103 112 111 115 116 84 114 97 99 107 105 110 103 65 80 73 167 82 97 119 80 97 116 104 217 38 47 109 97 47 71 101 116 73 116 101 109 84 114 97 99 107 105 110 103 68 101 116 97 105 108 115 79 110 101 84 78 84 83 101 99 117 114 101 173 67 111 110 116 101 110 116 76 101 110 103 116 104 205 1 50 169 85 115 101 114 65 103 101 110 116 160 163 68 97 121 17 165 77 111
...
```

https://github.com/TykTechnologies/tyk-pump/blob/master/storage/redis.go#L236-L238

```
Unpacked vals: [[222 0 27 166 77 101 116 104 111 100 164 80 79 83 84 164 72 111 115 116 191 101 115 98 73 110 116 101 114 110 97 108 76 66 46 112 111 115 116 115 118 99 115 46 99 111 109 58 57 48 57 48 164 80 97 116 104 183 47 109 97 47 83 105 110 103 112 111 115 116 84 114 97 99 107 105 110 103 65 80 73 167 82 97 119 80 97 116 104 217 38 47 109 97 47 71 101 116 73 116 101 109 84 114 97 99 107 105 110 103 68 101 116 97 105 108 115 79 110 101 84 78 84 83 101 99 117 114 101 173 67 111 110 116 101 110 116 76 101 110 103 116 104 205 1 50 169 85 115 101 114 65 103 101 110 116 160 163 68 97 121 17 165 77 111
...
```

It would be better to just return the length so that we can just see how many records returned.

**Comment by maciejwojciechowski** [comment] 2019-11-07 15:31
In debug logs for my gateway I see this
```
time="Nov 07 13:41:08" level=debug msg="Analytics returned: 2"
time="Nov 07 13:59:27" level=debug msg="Unpacked vals: [[222 0 29 166 77 101 116 104 111 100 163 71 69 84 164 72 111 115 116 171 104 116 116 112 98 105 110 46 111 114 103 164 80 97 116 104 163 47 105 112 167 82 97 119 80 97 116 104 163 47 105 112 173 67 111 110 116 101 110 116 76 101 110 103 116 104 0 169 85 115 101 114 65 103 101 110 116 181 80 111 115 116 109 97 110 82 117 110 116 105 109 101 47 55 46 49 57 46 48 163 68 97 121 7 165 77 111 110 116 104 11 164 89 101 97 114 205 7 227 164 72 111 117 114 13 172 82 101 115 112 111 110 115 101 67 111 100 101 205 1 147 166 65 80 73 75 101 121 168 48 48 48 48 48 48 48 48 169 84 105 109 101 83 116 97 109 112 146 206 93 196 35 60 206 38 145 54 48 170 65 80 73 86 101 114 115 105 111 110 173 78 111 110 32 86 101 114 115 105 111 110 101 100 167 65 80 73 78 97 109 101 163 97 112 105 165 65 80 73 73 68 217 32 98 100 49 57 49 49 100 101 51 99 54 48 52 99 53 52 52 102 51 56 51 56 99 54 48 49 56 54 102 97 99 53 165 79 114 103 73 68 184 53 100 99 52 49 101 52 55 51 50 48 101 52 48 48 99 51 102 97 49 51 98 100 48 167 79 97 117 116 104 73 68 160 171 82 101 113 117 101 115 116 84 105 109 101 0 167 76 97 116 101 110 99 121 130 165 84 111 116 97 108 0 168 85 112 115 116 114 101 97 109 0 170 82 97 119 82 101 113 117 101 115 116 160 171 82 97 119 82 101 115 112 111 110 115 101 160 169 73 80 65 100 100 114 101 115 115 170 49 55 50 46 49 56 46 48 46 49 163 71 101 111 131 167 67 111 117 110 116 114 121 129 167 73 83 79 67 111 100 101 160 164 67 105 116 121 129 165 78 97 109 101 115 192 168 76 111 99 97 116 105 111 110 131 168 76 97 116 105 116 117 100 101 203 0 0 0 0 0 0 0 0 169 76 111 110 103 105 116 117 100 101 203 0 0 0 0 0 0 0 0 168 84 105 109 101 90 111 110 101 160 167 78 101 116 119 111 114 107 132 175 79 112 101 110 67 111 110 110 101 99 116 105 111 110 115 0 176 67 108 111 115 101 100 67 111 110 110 101 99 116 105 111 110 0 167 66 121 116 101 115 73 110 0 168 66 121 116 101 115 79 117 116 0 164 84 97 103 115 148 174 116 121 107 45 104 121 98 114 105 100 45 114 112 99 172 107 101 121 45 48 48 48 48 48 48 48 48 188 111 114 103 45 53 100 99 52 49 101 52 55 51 50 48 101 52 48 48 99 51 102 97 49 51 98 100 48 217 36 97 112 105 45 98 100 49 57 49 49 100 101 51 99 54 48 52 99 53 52 52 102 51 56 51 56 99 54 48 49 56 54 102 97 99 53 165 65 108 105 97 115 160 169 84 114 97 99 107 80 97 116 104 194 168 69 120 112 105 114 101 65 116 146 206 93 205 93 188 206 38 146 138 108]]"
```

seems like it was only partially fixed. can you please check?

**Comment by furkansenharputlu** [comment] 2019-11-13 09:27
@maciejwojciechowski The logs you share are about gateway, the issue is mainly about `tyk-pump`. However, I have raised a PR to fix gateway logs as well. So, I am closing this issue.

**Closed by furkansenharputlu** 2019-11-13 09:27 UTC
Labels: Client request, Priority: Medium, bug

**Comment by maciejwojciechowski** [comment] 2019-11-13 14:26
@furkansenharputlu I am sorry but I don't see any option to enable 'debug' level logs on tyk-pump. can you please advice how to test this correctly? thanks

**Comment by furkansenharputlu** [comment] 2019-11-13 14:32
@maciejwojciechowski Set `TYK_LOGLEVEL` env var to `debug` then run pump.

**Comment by maciejwojciechowski** [comment] 2019-11-13 16:02
ok, thanks. verified fixed
```
[Nov 13 17:01:47] DEBUG redis: Analytics returned: 2
[Nov 13 17:01:47] DEBUG redis: Unpacked vals: 1
```
